name: 'Release Labeler'
on:
    milestone:
        types: [edited]

jobs:
    labeler:
        runs-on: ubuntu-latest
        steps:
            - name: View context attributes
              uses: actions/github-script@v3
              with:
                  script: console.log(context)
            - uses: actions/github-script@v3
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      console.log('hello');

                      const issues = await octokit.issues.listForRepo({
                        milestone: context.milestone.milestone.id,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        state: 'closed'
                      });

                      for (const issue of issues) {
                        console.log(issues);
                      }
